"""baseline

Revision ID: a9a854327f32
Revises: 
Create Date: 2026-06-04 21:27:28.317060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a854327f32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    op.create_index(op.f('ix_app_settings_key'), 'app_settings', ['key'], unique=True)
    op.create_table('llm_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('api_key', app.models.prospect.EncryptedString(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('api_type', sa.String(), nullable=True),
    sa.Column('extra_headers', sa.String(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority_order', sa.Integer(), nullable=True),
    sa.Column('daily_token_limit', sa.Integer(), nullable=True),
    sa.Column('tokens_used_today', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_reset_at', sa.Date(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_providers_id'), 'llm_providers', ['id'], unique=False)
    op.create_table('prospects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('subcategory', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('province', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('google_maps_url', sa.String(), nullable=True),
    sa.Column('phone_raw', sa.String(), nullable=True),
    sa.Column('phone_normalized', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('instagram_url', sa.String(), nullable=True),
    sa.Column('wa_valid', sa.Boolean(), nullable=True),
    sa.Column('is_claimed', sa.Boolean(), nullable=True),
    sa.Column('about_summary', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('price_level', sa.String(), nullable=True),
    sa.Column('hours', sa.String(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=True),
    sa.Column('is_permanently_closed', sa.Boolean(), nullable=True),
    sa.Column('photo_urls', sa.String(), nullable=True),
    sa.Column('total_photos', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('source_keyword', sa.String(), nullable=True),
    sa.Column('source_city', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospects_id'), 'prospects', ['id'], unique=False)
    op.create_index(op.f('ix_prospects_place_id'), 'prospects', ['place_id'], unique=True)
    op.create_table('scraper_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('target_categories', sa.String(), nullable=True),
    sa.Column('target_cities', sa.String(), nullable=True),
    sa.Column('max_per_day', sa.Integer(), nullable=True),
    sa.Column('delay_min_seconds', sa.Integer(), nullable=True),
    sa.Column('delay_max_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_config_id'), 'scraper_config', ['id'], unique=False)
    op.create_table('scraper_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('total_found', sa.Integer(), nullable=True),
    sa.Column('total_saved', sa.Integer(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scraper_progress_id'), 'scraper_progress', ['id'], unique=False)
    op.create_table('followups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('tone', sa.String(), nullable=True),
    sa.Column('provider_used', sa.String(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('contact_status', sa.String(), nullable=True),
    sa.Column('contacted_at', sa.DateTime(), nullable=True),
    sa.Column('last_followup_at', sa.DateTime(), nullable=True),
    sa.Column('followup_count', sa.Integer(), nullable=True),
    sa.Column('next_followup_date', sa.Date(), nullable=True),
    sa.Column('is_blacklisted', sa.Boolean(), nullable=True),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.Column('blacklist_reason', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_id'), 'pipeline', ['id'], unique=False)
    op.create_table('prospect_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('priority_tier', sa.String(), nullable=True),
    sa.Column('score_reasoning', sa.String(), nullable=True),
    sa.Column('recommended_service', sa.String(), nullable=True),
    sa.Column('pitch_angle', sa.String(), nullable=True),
    sa.Column('relevant_keywords', sa.String(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prospect_scores_id'), 'prospect_scores', ['id'], unique=False)
    op.create_table('website_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('website_status', sa.String(), nullable=True),
    sa.Column('is_mobile_friendly', sa.Boolean(), nullable=True),
    sa.Column('has_ssl', sa.Boolean(), nullable=True),
    sa.Column('has_ecommerce', sa.Boolean(), nullable=True),
    sa.Column('has_booking', sa.Boolean(), nullable=True),
    sa.Column('has_contact_form', sa.Boolean(), nullable=True),
    sa.Column('speed_score', sa.Integer(), nullable=True),
    sa.Column('design_quality_score', sa.Integer(), nullable=True),
    sa.Column('website_issues', sa.String(), nullable=True),
    sa.Column('website_summary', sa.String(), nullable=True),
    sa.Column('manual_reviewed', sa.Boolean(), nullable=True),
    sa.Column('manual_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('opportunity_type', sa.String(), nullable=True),
    sa.Column('opportunity_notes', sa.String(), nullable=True),
    sa.Column('estimated_value', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_reviews_id'), 'website_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_reviews_id'), table_name='website_reviews')
    op.drop_table('website_reviews')
    op.drop_index(op.f('ix_prospect_scores_id'), table_name='prospect_scores')
    op.drop_table('prospect_scores')
    op.drop_index(op.f('ix_pipeline_id'), table_name='pipeline')
    op.drop_table('pipeline')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_table('followups')
    op.drop_index(op.f('ix_scraper_progress_id'), table_name='scraper_progress')
    op.drop_table('scraper_progress')
    op.drop_index(op.f('ix_scraper_config_id'), table_name='scraper_config')
    op.drop_table('scraper_config')
    op.drop_index(op.f('ix_prospects_place_id'), table_name='prospects')
    op.drop_index(op.f('ix_prospects_id'), table_name='prospects')
    op.drop_table('prospects')
    op.drop_index(op.f('ix_llm_providers_id'), table_name='llm_providers')
    op.drop_table('llm_providers')
    op.drop_index(op.f('ix_app_settings_key'), table_name='app_settings')
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
